language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false