sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer self-update
  - composer update --prefer-source $PREFER_LOWEST

script:
  - vendor/bin/phpunit -c ./phpunit.xml.dist
  - vendor/bin/phpcs --standard=PSR2 src

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
