<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BsbDoctrineReconnect\Module'                      => __DIR__ . '/Module.php',
  'BsbDoctrineReconnect\DBAL\Connection'             => __DIR__ . '/src/BsbDoctrineReconnect/DBAL/Connection.php',
  'BsbDoctrineReconnect\DBAL\Driver\PDOMySql\Driver' => __DIR__ . '/src/BsbDoctrineReconnect/DBAL/Driver/PDOMySql/Driver.php',
  'BsbDoctrineReconnect\DBAL\Statement'              => __DIR__ . '/src/BsbDoctrineReconnect/DBAL/Statement.php',
);
